### ISSUE TITLE
Include iterative/dvc-doc-tutorial repo?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/example-repos-dev#10]
https://github.com/iterative/dvc-doc-tutorial

(Generate from this repo.)

**Comment by shcheklein** [comment]
Should be probably a checkbox for now at ticket about consolidating NLP examples/tutorials.

**Comment by jorgeorpinel** [comment]
True. Added

> - Check current Tutorial vs https://github.com/iterative/dvc-doc-tutorial

to https://github.com/iterative/dvc.org/issues/564#issue-481366484.

**Comment by shcheklein** [comment]
I've archived that repo, it's not used anywhere anymore I hope.
