### ISSUE TITLE
auto-generate CML example repos

### ISSUE THREAD

**Issue by casperdcl** [iterative/example-repos-dev#100]
Example repos are painful to update everywhere (e.g. iterative/cml.dev#178 touches all example repos). Should auto-generate them from one source similar to how https://github.com/iterative/example-repos-dev works.

- [ ] https://github.com/iterative/example_cml (/doc/start/github/)
  + [ ] https://github.com/iterative/cml_base_case (/doc/start/github/, /doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_dvc_case (/doc/cml-with-dvc, /doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_tensorboard_case (/doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_cloud_case (/doc/usage?tab=GitHub#example-projects)
- [ ] https://gitlab.com/iterative.ai/example_cml (/doc/start/gitlab/)
  + [ ] https://gitlab.com/iterative.ai/cml-base-case (/doc/start/gitlab/, /doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-dvc-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-tensorboard-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-cloud-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-runner-example (/; “CML Use Cases” section; “CML Runner Cloud” tab; “GitLab” switch position)
- [ ] https://bitbucket.org/iterative-ai/example-cml (/doc/start/bitbucket/)
  + [ ] https://bitbucket.org/iterative-ai/cml-base-case (/doc/start/bitbucket/, /doc/usage?tab=Bitbucket#example-projects-2)
  + [ ] https://bitbucket.org/iterative-ai/cml-cloud-case
  + [ ] runner-related demo repos coming soon (https://github.com/iterative/cml.dev/issues/349)
- [ ] https://github.com/iterative/cml-runner-base-case (/)

**Comment by iesahin** [comment]
Moved and will be tracking here. Do you have any specific requirements for repositories? Would a simple `generate.bash` script suffice? @casperdcl

**Comment by iesahin** [comment]
I think you prefer to have a single `generate` script for all these repositories, right? @casperdcl

**Comment by casperdcl** [comment]
Yes exactly. Reordered the list a bit to reflect that most should be based on the current https://github.com/iterative/example_cml

**Comment by casperdcl** [comment]
@iesahin 

1. rename `master` to `main` using the GH interface so people get redirected appropriately
2. we need to keep all branches as they are (i.e. keep the associated PRs open as examples of what PRs look like)
3. ideally only auto-update *one* (i.e. the latest) `main` commit from one unified codebase

I'm open to other suggestions for (3). Basically requirement (2) is quite different from the DVC example repos and I don't see a neat way around it.

**Comment by iesahin** [comment]
Let me investigate the repositories a bit. AFA I understand you want `generate.sh` to clone one (private?) repository generate other repositories from that by applying the changes. 

I want to use an approach as simple as possible, you'll keep project files in a repository (`iterative/example_cml` or some base repository) and have a directory structure similar to this: 

```
   example-cml-generator/
     example-cml/
       main/
       experiment/
       experiment-1/
....
    cml_dvc_case/
       main/
       experiment/
       ....
```

From these, it will apply `cml_dvc_case/main` to the base repository and get `main` branch, then apply `experiment` to this `main` branch and get `experiment` branch, etc. 

Please let me know if there are more complex relationships between the repositories.

**Comment by 0x2b3bfa0** [comment]
_Note: as per https://github.com/iterative/cml/issues/890#issuecomment-1106118830,  https://gitlab.com/iterative.ai/cml-base-case was broken in every imaginable way._

**Comment by 0x2b3bfa0** [comment]
Closing in favor of https://github.com/iterative/cml-examples-dev/issues/6

**Comment by 0x2b3bfa0** [comment]
@casperdcl, it probably doesnt (?) 🤔🐶

**Comment by 0x2b3bfa0** [comment]
> _What's the status?_

The new examples are less broken than the old ones, although that doesn't necessarily[^1] imply that they work.

[^1]: Weasel words, read: “they're also broken, but in minor ways by comparison”

**Comment by casperdcl** [comment]
I'd say this was closed in favour of https://github.com/iterative/cml-examples-dev/issues/9 instead :)

**Comment by 0x2b3bfa0** [comment]
Or maybe https://github.com/iterative/cml-examples-dev/issues/16?
