### ISSUE TITLE
`example-get-started`: include flexible plots

### ISSUE THREAD

**Issue by pared** [iterative/example-repos-dev#124]
### Report

Related: iterative/dvc.org#3691 
Related: iterative/dvc#7477

We should probably showcase flexible plots in our `example-get-started` repo.

**Comment by shcheklein** [comment]
@pared @daavoo good idea, do you have any specific plots in mind for this?

**Comment by dberenbaum** [comment]
@pared Sorry, I forgot that I already started this in https://github.com/iterative/example-repos-dev/pull/117 😅

**Comment by shcheklein** [comment]
@dberenbaum @pared yep, that's right, I also forgot about that PR!

**Comment by shcheklein** [comment]
@dberenbaum does it need any updates?

**Comment by shcheklein** [comment]
@dberenbaum I guess we close this now?
