### ISSUE TITLE
Reverse order of `deploy.sh` and `generate.sh`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/example-repos-dev#129]
I always find it confusing when developing on this repo that I have to deploy the code I'm still developing before generating the repo locally. I end up having to modify the scripts so I don't accidentally deploy the untested code but also can still use it to generate a local copy of the repo for development. Would it make sense to modify the scripts so that `generate.sh` uses whatever code is locally available and `deploy.sh` is only used as part of the final deployment process (maybe as part of a GH action when merged)?

**Comment by shcheklein** [comment]
It makes sense, I would though probably make `generate.sh prod` or something that still downloads from S3 (so that we can be 100% that we do exactly same steps as users would do).
