### ISSUE TITLE
`example-get-started` : use tar instead of zip

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/example-repos-dev#13]
I think we're using ZIP so Windows users can use the example-get-started repo

https://github.com/iterative/example-repos-dev/blob/9ec8211ad7da6ec6f219a407526e945b3c9c5764/example-get-started/deploy.sh#L17-L19

But a) I can't run the above command from Windows (i.e. generating the repo, because `zip` isn't available on Win cmd or any terminal), and most importantly, b) `unzip` is also not a command shipped with Windows. You need to install it on some other console such as Git Bash using Chocolatey, etc.

https://github.com/iterative/example-repos-dev/blob/9ec8211ad7da6ec6f219a407526e945b3c9c5764/example-get-started/generate.sh#L82-L84

Why not just use something more Linux friendly that we can also install on Windows anyway? Meaning `tar`

**Comment by jorgeorpinel** [comment]
This will imply updating the docs at dvc.org/doc as well.

**Comment by shcheklein** [comment]
yep, agreed. The only thing I had in mind that `zip` (even though CLI is not available) is a bit more familiar to win users, and even Explorer itself can open it as far as I remember.

On the other hand, what are downsides of using zip? I think for Linux users it does not make any difference, right?

**Comment by jorgeorpinel** [comment]
Yes, Window Explorer can open ZIP files, this is true. So we could keep these and just mention in a bunch of places that for windows some of the commands have to be done via browser and UI instead of CLI. I would still prefer tar. Most devs are familiar with tars and tarballs, I think.

No downside for Linux, just weird haha.

**Comment by shcheklein** [comment]
Let's do tar - I'm fine with that!

**Comment by shcheklein** [comment]
Better to avoid a lot of notes everywhere about Windows

**Comment by jorgeorpinel** [comment]
Agree. Will do!
