### ISSUE TITLE
experiments: start without `dvc pull`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/example-repos-dev#163]
Can the initial notebook stage not rely on dvc pull? Ideally, I don’t even think we should use dvc get-url but instead download the data directly inside the notebook so you start completely fresh and it doesn’t look like there’s any existing dvc knowledge or special stuff happening before you can start logging experiments.

**Comment by daavoo** [comment]
After this time I am not sure it is worth it. There was no signal of this being an issue.

Also, I think that the current workflow is equally valid for an important part of users. People using dvc for data management and moving to experiments.
