### ISSUE TITLE
experiments: avoid dvc cli commands inside the notebook

### ISSUE THREAD

**Issue by dberenbaum** [iterative/example-repos-dev#164]
The CLI commands for comparing and applying experiments at the end of the notebook is still pretty awkward. This is mostly something we need to solve on the product side. I’d probably see if we can avoid at least doing dvc exp apply inside the notebook — it seems awkward to apply a different git commit to your workspace while actively working in a notebook, and it will break when the experiment names change.

**Comment by daavoo** [comment]
`dvc exp apply` is no longer called inside the notebook. Do you think we should also remove `exp show`?

**Comment by dberenbaum** [comment]
No, I think that's fine for now.
