### ISSUE TITLE
example-get-started is broken with latest DVC

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/example-repos-dev#17]
> From https://github.com/iterative/dvc.org/issues/1743#issuecomment-730726776

```console
$ git@github.com:iterative/example-get-started.git
...
$ cd example-get-started
$ dvc fetch
ERROR: failed to fetch data from the cloud - Lockfile 'dvc.lock' is corrupted.
```

**Comment by shcheklein** [comment]
What DVC version do you use? It should be be fixed in the most recent one.

**Comment by jorgeorpinel** [comment]
1.9.1 on Windows (latest)

**Comment by shcheklein** [comment]
the latest version is 1.10 something. if it's not updated on Windows then we have a problem with Win releases cc @efiop

**Comment by jorgeorpinel** [comment]
Ah I was wrong, you're right. Works with 1.10.1 which I got from https://github.com/iterative/dvc/releases/

The problem is that the dvc.org home page download button is stuck at 1.9.1 for all platforms, it seems.

**Comment by jorgeorpinel** [comment]
Opened iterative/dvc.org/issues/1964, resolving here.

**Comment by yakushechkin** [comment]
I use the latest dvc version [DVC version: 1.11.16 (pip)] and have got the same issue while following the [installation](https://github.com/iterative/example-get-started) steps:
OS: Mac OS Mojave 10.14.6
```
$ dvc pull
Everything is up to date.                                             
ERROR: failed to pull data from the cloud - Lockfile 'dvc.lock' is corrupted.
```

**Comment by efiop** [comment]
@yakushechkin example-get-started is migrating to dvc 2.0, so it is no longer compatible with older dvc versions. We plan on releasing 2.0 on Wednesday. You could try `pip install --pre dvc` to install dvc pre-release. Sorry for the inconvenience.
