### ISSUE TITLE
experiments: rename metrics from "Average Precision" to "Dice Metric" in README

### ISSUE THREAD

**Issue by alex000kim** [iterative/example-repos-dev#174]
here: https://github.com/iterative/example-get-started-experiments/blob/3990a0ca721e7974a6126e89abc05bba2a260d83/README.md?plain=1#L2

**Comment by daavoo** [comment]
I think It might just be that the repo is private?

**Comment by alex000kim** [comment]
You are right - it works now :) 
We still need to rename "average precision" to "dice coefficient".

**Comment by alex000kim** [comment]
@daavoo do you by any chance know how to auto-modify branch name in README? 
E.g. this one still shows the metric from the `main` branch https://github.com/iterative/example-get-started-experiments/blob/tune-architecture/README.md
