### ISSUE TITLE
Error dvc get

### ISSUE THREAD

**Issue by rfluisa** [iterative/example-repos-dev#18]
I followed the hands-on tutorial some days ago and now I've got an error when trying to download the data.xml from dataset-registry.

Could it be an error with the data.xml.dvc file?

dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data/data.xml

ERROR: failed to get 'get-started/data.xml' from 'https://github.com/iterative/dataset-registry' - '../../../../../tmp/tmp0dar7q9ddvc-clone/get-started/data.xml.dvc' format error: extra keys not allowed @ data['outs'][0]['size']

**Comment by efiop** [comment]
@rfluisa You are likely using an old dvc version. Please upgrade to the latest version `1.11.10` and try again.
