### ISSUE TITLE
experiments: DVC remotes with the same name

### ISSUE THREAD

**Issue by alex000kim** [iterative/example-repos-dev#180]
In `generate.sh` we create two DVC remotes (HTTP and S3) with the same name `storage`:
https://github.com/iterative/example-repos-dev/blob/master/example-get-started-experiments/generate.sh#L61-L63
I am not sure if it's an issue, but it looks like one to me.

**Comment by daavoo** [comment]
I think it should be fine (might be wrong), as the one with `--local` takes priority for DVC when resolving the config, and it is not committed to the generated repo (https://github.com/iterative/example-get-started-experiments/blob/main/.dvc/config)

**Comment by shcheklein** [comment]
Yes, it should be fine. We do the same in the `example-get-started` repo:

https://github.com/iterative/example-repos-dev/blob/master/example-get-started/generate.sh#L73-L75
