### ISSUE TITLE
`experiments`: Use fixed test set 

### ISSUE THREAD

**Issue by daavoo** [iterative/example-repos-dev#188]
We are doing a random split so whenever we change the `data_split` stage (i.e adding more data or changing the percentage), we evaluate on a different set of images and generate different results. 

This is a problem because the comparison of metrics is invalid as they come from different datasets.
It has also a minor but a more visual problem that we can't compare predictions in Studio:

<img width="1792" alt="Captura de pantalla 2023-02-16 a las 13 28 30" src="https://user-images.githubusercontent.com/12677733/219365277-fd0d27b8-e2ad-465f-8ccb-3525c4b23713.png">

**Comment by dberenbaum** [comment]
Why doesn't this solve it?

https://github.com/iterative/example-repos-dev/blob/72683ff2aa88091a53760b093a5fe1afdaeca039/example-get-started-experiments/code/src/data_split.py#L15

**Comment by daavoo** [comment]
> Why doesn't this solve it?
> 
> https://github.com/iterative/example-repos-dev/blob/72683ff2aa88091a53760b093a5fe1afdaeca039/example-get-started-experiments/code/src/data_split.py#L15

The point is that even different split percentages and modifications to the source dataset should not alter the dataset that is used to compare experiments.

That is why I suggest to have a hardcoded list of images for testing and use it to compute the metrics that are used to compare experiments.
