### ISSUE TITLE
Include desc field into the file description

### ISSUE THREAD

**Issue by mvshmakov** [iterative/example-repos-dev#19]
Introduced https://github.com/iterative/example-get-started/pull/5#issuecomment-763154743.

[`desc` field](https://dvc.org/doc/user-guide/dvc-files/.dvc#output-entries) can be both useful for the newbies and for the Viewer team in order to test parsing of this field. Please, include it in the `.dvc` file description in the next version of the example repository.

**Comment by dberenbaum** [comment]
Is this still needed? I could probably add it if we already need to do a quick fix for #28.

**Comment by shcheklein** [comment]
Yep, let's add if we are going to regenerate the project with the #28 . Thanks 🙏
