### ISSUE TITLE
Automate deploy

### ISSUE THREAD

**Issue by daavoo** [iterative/example-repos-dev#200]
We currently rely on people generating the repo locally or in codespaces and then manually running the commands described (i.e. https://github.com/iterative/example-repos-dev/blob/master/example-get-started-experiments/README.md) in order to "deploy" the new version of the repo.

At least for [`example-get-started-experiments`](https://github.com/iterative/example-repos-dev/tree/master/example-get-started-experiments), which is the one I am familiar with, I don't see any reason why we should not automate this process in a GitHub workflow on `push: main` that generates and deploys the model (we can set up a CML runner for the GPU)

**Comment by daavoo** [comment]
> , I don't see any reason why we should not automate this process 

Any downsides/thoughts @shcheklein @dberenbaum ?

**Comment by shcheklein** [comment]
No downsides. There are some steps that needs to be taken care of on the Studio side sometimes (reparse, adjust Views columns that we need to keep an eye on). Also, primarily the reason was that we don't have time for this, it was not considered critical.

**Comment by daavoo** [comment]
btw this would be also good to ensure that the deployed version is up to date.
It looks like the current https://github.com/iterative/example-get-started-experiments was deployed from a branch that was not up to date with master

**Comment by dberenbaum** [comment]
Prioritizing this for a couple reasons:

1. Sick of spending time manually deploying or fixing issues deploying
2. Means we can deploy more frequently and ensure it works with newer versions of dvc
