### ISSUE TITLE
Register models in the example repos to see them in the MR

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#203]
Feedback by @omesser in one of the Studio tickets.

**Comment by aguschin** [comment]
Updated https://github.com/iterative/example-get-started-experiments/pull/126

**Comment by aguschin** [comment]
Adding it to http://github.com/iterative/example-get-started is blocked by https://github.com/iterative/dvc/issues/9527

**Comment by shcheklein** [comment]
> Updated https://github.com/iterative/example-get-started-experiments/pull/126

I think we can automate this with `gh` and `git` to create and push tags, PRs, etc?

**Comment by aguschin** [comment]
We just discussed this with @daavoo  in https://github.com/iterative/example-repos-dev/pull/204#issuecomment-1570175103. I think we can, but I see the value in showing that Studio created that PR.

Besides, if you TAL at the README in that repo, it requires one to go to Studio to create an experiment (changing some param), that creates PR and runs CI/CD. If we want to get this repo generated automatically, we need to automate both.

**Comment by shcheklein** [comment]
@aguschin yep, okay, let's try to keep it this way. Let's update the README / instruction to how to deploy the project?

**Comment by aguschin** [comment]
@shcheklein, can you please check out this https://github.com/iterative/example-repos-dev/pull/204/files?

I've update README to tell about MR PR, and dev README for us to re-generate the repo right.

**Comment by shcheklein** [comment]
Do we consider this is done? (and we agree that we do these steps manually for both example repos?)

**Comment by aguschin** [comment]
No, but #207 will close this.
