### ISSUE TITLE
Add deployment of example-get-started-experiments model

### ISSUE THREAD

**Issue by dberenbaum** [iterative/example-repos-dev#222]
Add a CI job that uses model registry to deploy the example-get-started-experiments model. Nice to have would be using Sagemaker for deployment.

**Comment by daavoo** [comment]
Added a simple deployment pattern in https://github.com/iterative/example-repos-dev/pull/229 . It just creates a new endpoint whenever a new version is registered.

The stages in the registry are not handled at all, I preferred to discuss what would make sense to simulate a "real" use case.

A proposal I have is to use a pattern like the following:

- MR: Registering version
Sagemaker: Creates a model in Sagemaker but **does not create** an endpoint.

- MR: Assigning stage.
Sagemaker: Creates and links endpoint to the model created when registering a version.
Depending on the stage, use a different endpoint config (i.e. larger instance type for prod, smaller for dev)

- MR: Updating stage.

I think this should remove the endpoint from the previous stage and create a new one.

**Comment by dberenbaum** [comment]
Fixed in #233
