### ISSUE TITLE
Unclear reference to a pull request in example-get-started-experiments README.md

### ISSUE THREAD

**Issue by tibor-mach** [iterative/example-repos-dev#230]
[Here](https://github.com/iterative/example-repos-dev/blob/af382934c4bc841463ba085b4387826205ca7b7a/example-get-started-experiments/code/README.md?plain=1#L111C1-L115C114) we have a reference in the README.md to a pull request which adds a model to the studio model registry. But there are no pull requests in that link, it just is just a link to the github pull requests page.

I am not sure if @aguschin meant that if you run the `dvc-studio` GH Actions workflow that you will get a pull request there or if it was supposed to actually refer to a specific pull request. Either way, I think this might be confusing to people who want to try things out.

I can update it to make it clearer, but please @aguschin let me know what the meaning was. I guess it was the first option, but I don't want to mess it up without asking. Thanks!

**Comment by dberenbaum** [comment]
There's discussion about it in #204, but it looks like it should have been dropped as part of #207. @tibor-mach Feel free to submit a PR to drop it.

**Comment by dberenbaum** [comment]
Fixed per #233
