### ISSUE TITLE
Replace `virtualenv` with `python3 -m venv` in README.md

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#26]
Is there a reason [the example's README.md](https://github.com/iterative/example-get-started/blame/master/README.md#L31) uses `virtualenv`? It needs to be installed separately. It has more features but for basic use, `python3 -m venv` can replace it I think.

**Comment by shcheklein** [comment]
@iesahin one of the reasons usually is that `virtualenv` also installs `wheels` automatically. It means for example that DVC can be installed w/o compiling stuff from sources, way faster. 

I would also prefer to use `python3 -m venv`, but I'm not sure yet what to think how to deal with the `wheels` package. Do additional command? make is part of the requirements? We need to research this a bit.

This decision can affect a lot of places in the docs, btw.

**Comment by iesahin** [comment]
@shcheklein I believe that's a Debian bug that I accustomed to work around by `pip install wheel` after activating the environment.

Adding it to `requirements.txt` doesn't work. Although [there are ugly hacks](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip) we can't specify the installation order and even if we could, the build phase is earlier so it will look for an already installed `wheel`. 

I'd prefer to mention `pip install wheel` as a command, rather than specifying a 3rd party package. Creating the virtual environment can also be a link to a common document, telling the reasons and various ways. For example, in Docker I prefer not to use `venv`, as the container itself is _virtual to the root._ 

There is a new `python -m venv` option in 3.9. `--upgrade-deps` will probably fix this. Let me check that.

**Comment by iesahin** [comment]
[Debian Bullseye](https://wiki.debian.org/DebianBullseye) contains Python 3.9. I installed `python3` and `python3-venv` packages, then tested to create the environment using `python -m venv --upgrade-deps env`. 

![levinas-210320-121522](https://user-images.githubusercontent.com/476310/111865200-a0b08000-8976-11eb-91ae-7a4a6bfa2c4c.png)

It installs from the wheels without error. 
 
![levinas-210320-121551](https://user-images.githubusercontent.com/476310/111865212-b0c85f80-8976-11eb-9836-ad1746246940.png)

**Comment by iesahin** [comment]
BTW, it looks like the bug causing packages not to be installed from wheels is fixed in Debian stable too. 

![levinas-210320-123544](https://user-images.githubusercontent.com/476310/111865582-fb4adb80-8978-11eb-8b97-edbdfe29eb50.png)

This is after `apt install python3 python3-venv` on a clean Debian stable container, with Python 3.7. The problem was that the default setuptools shipped with Python was too old and required update. It looks we can simply use `python3 -m venv` for virtual environments.

**Comment by shcheklein** [comment]
>  It looks we can simply use `python3 -m venv`

hmm, that's what I get after the clean `python3 -m env` on Python 3.9.2:

```
(.env) √ Projects/test-venv % pip freeze
(.env) √ Projects/test-venv % pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 53.0.0
```

`wheel` package is not installed.

**Comment by iesahin** [comment]
In Ubuntu/Debian, at least,  [`python3-venv`](https://packages.ubuntu.com/focal/python3.8-venv) package depends on [`python-pip-whl`](https://packages.debian.org/stretch/python/python-pip-whl) that seems to enable `bdist_wheel` for `pip`. 

In a new Ubuntu 20.04 container with only  `python3` and `python3-venv` packages installed with `apt`, after creating the environment and activating, I get:

```
(hello) root@3d61f038b821:/hello# pip3 list
Package       Version
------------- -------
pip           20.0.2
pkg-resources 0.0.0
setuptools    44.0.0
```

Installation of, e.g., `pillow` is using just the`.whl` package:

```
(hello) root@3d61f038b821:/hello# pip3 install pillow
Collecting pillow
  Downloading Pillow-8.2.0-cp38-cp38-manylinux2014_aarch64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 1.4 MB/s
Installing collected packages: pillow
Successfully installed pillow-8.2.0
```

`wheel` is not installed but that functionality seems to be present after installing `python-pip-whl`. 

@shcheklein

**Comment by shcheklein** [comment]
@iesahin should we update this and/or close?

**Comment by iesahin** [comment]
I couldn't decide on this. Maybe using `-m venv` in the new docs and waiting for the issues is a better strategy?

@shcheklein

**Comment by shcheklein** [comment]
yeah, my only concern that issue can be "build is too slow" - it'll take time for us to realize this. I'm fine to wait for that though. The only thing I would recommend is to try to build/install DVC and other repos on a clean machine (no wheel cache, etc).

**Comment by shcheklein** [comment]
Closing for now.
