### ISSUE TITLE
Default branch for example-get-started (and others)

### ISSUE THREAD

**Issue by dberenbaum** [iterative/example-repos-dev#32]
My git config sets main as my default branch, which breaks the instructions to publish example-get-started (since I have no master branch to push by default). Ideally, we would update the example-get-started default branch, but we may need to check that we don't break anything in the tutorial. At minimum, we should explicitly checkout a specific branch before publishing.

We should also keep this in mind for other repos in development.

**Comment by iesahin** [comment]
I think I can update the default branch of https://github.com/iterative/example-get-started to `main` in the scripts, but #50 should be done before. (Otherwise custom changes will be overwritten.) In `get-started-experiments`, I used `main` and will continue to do so in others.

**Comment by shcheklein** [comment]
I think this is done.
