### ISSUE TITLE
dvc-get-started: Rename `main` branch to `pipeline`

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#39]
The `main` branch looks as if it's _the primary_ use case. Although this might be true in the past for `example-get-started`, we have more than one use cases that need attention now. (`checkpoints`, `experiments` and maybe `studio`.)

Instead of selecting one of these as `main`, the naming should emphasize the different use cases. 

Related #34

**Comment by shcheklein** [comment]
Some context from the top of my head. `main` should be about the current-best-model. We assume that people do experiments (trying new approaches) in the feature branches, and when it's clear that the new model is better (e.g. via CML report or Studio or regular GH PR review), they merge that into the `main` to then deploy it.

In case of the example repos, we have't used branches at all so far (except for the the most recent `example-get-started`, which is btw not codified yet - I need create a ticker I guess). We were simplifying them as much we can. My take it would be confusing a bit if we don't have `main`/`master` at all. Also, it's fine to have `main` focused on some default scenario (e.g. step-by-step intro into experiment - it can be even two commits, doesn't probably matter).

**Comment by iesahin** [comment]
We use the repository for exposition, and this is not only for finding _the best_. There is not a _best way to use_ DVC. Folks can use it for data access, data versioning, pipeline/dependency management, experiments, checkpoints, or any combination of these. Combining all these into a single branch/project seems a bit awkward and selecting one of them as _main_ makes the other use cases secondary. 

I would like the users to see that _there is no single way to use DVC_, rather than selecting one and promoting it to `main`. Most of the features are orthogonal and having different branches emphasizes it in my (not-so-strong) opinion. 

We can select one of them, like `experiments` and call it `main`, but when a user visits a repository, it's much more likely to check other branches if the branch name is not `main`/`master`. 

I don't propose to have no `main`, instead it can contain long and descriptive introduction text with links to other branches/documentation/containers (#40).

**Comment by shcheklein** [comment]
I guess, my point that we should be hiding from the repos we expose as many "organizational" (doc specific mechanics) decisions as possible. Each repo should feel very natural from the end-users perspective. They won't understand (at least immediately) why do we have multiple branches if those are completely different projects.

The same applies to the params - it's better not to expose/mix/include params that we need to create one type of the project or another. All params (and their evolution) ideally should stay simple and natural. It's better to move our internal machinery to the dev repo that generates it.

**Comment by shcheklein** [comment]
> I don't propose to have no main, instead it can contain long and descriptive introduction text with links to other branches/documentation/containers (#40).

this, for example, creates a special type of project, docs project rather than something regular most users deal with.

**Comment by jorgeorpinel** [comment]
Vote for choosing one scenario as the "main" one (or simplest one) and leaving it in the `main` branch.

**Comment by dberenbaum** [comment]
We previously had a very linear get started section and a corresponding repo. Now we are expanding to include ideas like checkpoints and proposing multiple entrypoints for users to get started, so having a single repo branch that feels natural with a linear progression is probably impossible. We can have multiple copies of the repo for different entrypoints or different branches.

As has been suggested before, I think we need to start writing the docs before over-optimizing on the repo structure. Once we have at least a rough start on the revised docs, we should have a better idea of how to structure the repos.

**Comment by iesahin** [comment]
I also think going for _multi-repo_ setup instead of _multi-branch_ may feel more natural. I'll have branches in the repository for the time being, then revise the documentation and move each branch to a separate repository. 

If all of these are generated from a single script in `example-repos-dev`, I think it doesn't matter (maintanence-wise) whether we have multiple branches or multiple repositories.

**Comment by iesahin** [comment]
I moved branches into repositories. `dvc-get-started` split into 3 and `main` branch became [`get-started-pipelines` ](https://github.com/iterative/get-started-pipelines) repository.
