### ISSUE TITLE
dvc-get-started: Add `main` branch that documents all other branches with Readme

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#40]
The `main` branch should only document all other branches in Readme. It should list all branches, tags, parameters, code and directory structure of the project. 

Related: #34 
Related: #39

**Comment by shcheklein** [comment]
See my 2cs here - https://github.com/iterative/example-repos-dev/issues/39#issuecomment-841516478

But we can try this approach as well. I'm a bit afraid that it might confuse folks. Ideally we should then imitate `main` as a `production` branch.

**Comment by jorgeorpinel** [comment]
Another alternative is what we have in https://github.com/iterative/dvc-checkpoints-mnist/blob/live/README.md  — a section that lets you switch branches from the README:

![image](https://user-images.githubusercontent.com/1477535/118346997-63dfb000-b505-11eb-9b51-239e6ca2c751.png)

**Comment by iesahin** [comment]
I think it might be more appropriate to have multiple repositories with the README files linking to each other. When someone learning experiments wants to dive into data access, they can follow the other repository.

**Comment by iesahin** [comment]
I've split the repository into 3 in c425572, each of the `pipelines`, `checkpoints`, `experiments` now produce a different repository. `experiments` branch is using Fashion-MNIST dataset. I can add more repositories this way. 

Each of these repositories will have a single branch called `main`. Is this OK?

**Comment by shcheklein** [comment]
That's great, I put some minor comments. The PR becomes too large to review. Ideally we should be splitting it into steps. No one can review so much stuff at once :)

**Comment by iesahin** [comment]
It's becoming like an 18-armed octopus 🐙. I mean octodecimopus 🤪

**Comment by iesahin** [comment]
Now we have 3 different repositories: 

- `https://github.com/iterative/get-started-pipelines`
- `https://github.com/iterative/get-started-experiments`
- `https://github.com/iterative/get-started-checkpoints`

There is a single script to set the environment and run `generate-X` scripts. It also produces `push-X.bash` script for the generated repository. 

Related #34
