### ISSUE TITLE
get-started-checkpoints: Convert checkpoints' examples to indefinite-training

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#43]
When the `epochs` value is 0, the training should continue indefinitely in checkpoints tags. We can set this as the default to show checkpoints' usage without a set ending point. 

## Todo

- [x] Runs the training indefinitely when `train.epochs=0`
- [x] Move all model and logs recording code to a callback (#47)

_Originally posted by @iesahin in https://github.com/iterative/dvc-checkpoints-mnist/issues/13#issuecomment-841686105_

**Comment by iesahin** [comment]
The first part for this is done in #45 but it has errors like below. So an update #47 is needed. 

![Screenshot_20210525-214311_Termux](https://user-images.githubusercontent.com/476310/119670460-952f7880-be41-11eb-9a6f-dd801cff7e24.jpg)

**Comment by iesahin** [comment]
This is done in 7fbbd0e.

**Comment by iesahin** [comment]
Supposing we have a pipeline like:

```
prepare ➡️ train ➡️ evaluate
```

and we put a checkpoint at the end of the `train` stage,

```yaml
train:
    - outs: 
       - model.h5:
         checkpoint: true 
```

and run the pipeline indefinitely _within the `train.py`_:

```
prepare ➡️ train 🏁 evaluate
```

DVC never to runs the `evaluate` stage if use indefinite training in `train.py`. 

I think indefinite training should be specified using 

```bash
while true ; do dvc exp run -S train.epochs=1 ; done
```

instead of the code itself. 

@dberenbaum @shcheklein

**Comment by dberenbaum** [comment]
Solely for purposes of the getting started doc, I don't think the separate `evaluate` stage is needed here. We are getting metrics on validation data at each checkpoint within `train`, and I don't think a final evaluation on separate holdout data is adding much.

As a broader dvc issue, checkpoints is pretty wonky if the checkpoint isn't in the final pipeline stage. The `make_checkpoint` workflow breaks down if you have some final holdout data on which you want to evaluate the model (or any other downstream stage). We might want to open a discussion in the dvc core repo about this. I wonder if we need something to mark that a checkpoints experiment is finished 🤔 .

There are at least two options in this case:
* Do something like the `while true ; do dvc exp run -S train.epochs=1 ; done` workflow that @iesahin mentioned (similar to the `basic` branch of the checkpoints repo).
* Run `dvc exp run --downstream evaluate` (somewhat related to https://discuss.dvc.org/t/experiments-with-checkpoint/744/4).

I don't think either of these are _necessary_ for getting started, but we may want to document a workflow like this in the user guide.

**Comment by dberenbaum** [comment]
> As a broader dvc issue, checkpoints is pretty wonky if the checkpoint isn't in the final pipeline stage. The `make_checkpoint` workflow breaks down if you have some final holdout data on which you want to evaluate the model (or any other downstream stage). We might want to open a discussion in the dvc core repo about this. I wonder if we need something to mark that a checkpoints experiment is finished 🤔 .

https://github.com/iterative/dvc/discussions/6104

**Comment by iesahin** [comment]
I have merged `train` and `evaluate` stages in `get-started-experiments` and will do the same in `get-started-checkpoints`. This will solve the issue at hand but we probably need some paranthesis-like control facility for the checkpoints, like `begin-checkpoint` and `end-checkpoint` in different stages.

**Comment by shcheklein** [comment]
I think this is outdated.
