### ISSUE TITLE
get-started-checkpoints: Create a new `DVCCallback` that saves the model and metrics before `signal-file` or `make_checkpoint` 

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#47]
Currently the [`get-started-checkpoints`](https://github.com/iterative/get-started-checkpoints) uses Tensorflow callbacks to make a checkpoint after each epoch. But saving the model and metrics causes an error if `make_checkpoint` and `signal_file` runs before them. So the project should save the model and metrics within the callback, not after it. 

Related with #45

**Comment by shcheklein** [comment]
@iesahin could you expand on this a bit? I wonder if it's something we should communicate back to the team?

**Comment by iesahin** [comment]
I wrote something similar to [this](https://github.com/iterative/dvclive/pull/69/files) for all ways of using checkpoints. I don't know if TF/Keras callbacks can be distributed with DVC or should we submit them to TF.contrib. 

I don't think the core team should modify anything but we need to be clear about the use of checkpoints and caveats in the docs. A special _Checkpoints for Tensorflow_ document (and also all other popular libraries) may be useful.

**Comment by dberenbaum** [comment]
One takeaway is that we should clarify that all outputs must be written before generating a checkpoint.

Another takeaway is that we should have examples or explanations for two broad scenarios:
1) Loops/iterators where writing the outputs and making the checkpoints happens within the loop:
```python
while True:
    model.fit()
    model.save()
    make_checkpoint()
```
2) Callback functions where everything happens in the callback:
```python
class DVCCallback(Callback):
    def on_epoch_end(self, epoch):
        self.model.save()
        make_checkpoint()

model.fit(callback=DVCCallback)
```

We might also want to consider introducing DVCLive first since it can take care of all of these steps and have built-in integrations for TensorFlow, PyTorch, etc..

**Comment by shcheklein** [comment]
thanks! and thanks @dberenbaum . I still feel a bit lost (probably means I don't have knowledge on how DVCLive is organized).

> But saving the model and metrics causes an error if `make_checkpoint` and `signal_file` runs before them. So the project should save the model and metrics within the callback, not after it.

could you clarify a bit on this? show an example (similar to Dave's)?

> We might also want to consider introducing DVCLive first since it can take care of all of these steps and have built-in integrations for TensorFlow, PyTorch, etc..

you mean in the example itself, start right from the DVCLive?

**Comment by dberenbaum** [comment]
> you mean in the example itself, start right from the DVCLive?

Yup

**Comment by iesahin** [comment]
This is also related with iterative/dvc.org#2509 

I have made the necessary changes in 7fbbd0e565b193ecdcffeb409971b8d9273f2b6d

**Comment by shcheklein** [comment]
Hmm ... I'm still lost re the error you had before.

Also, it looks like we pretty much implemented the logger on our own. Do we need to and why?

(please assume I don't know that much about `dvclive`)

**Comment by iesahin** [comment]
> could you clarify a bit on this? show an example (similar to Dave's)?

In PyTorch, we can use a loop to update the model epoch by epoch and in this loop we can use ˋmake_checkpointˋ or _signal file_ to create new checkpoints. 

Tensorflow/Keras uses callbacks to run custom code in certain points in training. The ˋCallbackˋ class has ˋon_epoch_beginˋ, ˋon_epoch_endˋ... methods to overload and we need to use them to save the checkpoints. These callbacks are compiled into the model _before_ training. 

So when we want to save the model/checkpoint/logs at the end of each epoch, we need to supply this as a callback.

Normally, we would do

ˋˋˋpython
while True:
    model.train(data, epochs=1)
    make_checkpoint()
ˋˋˋ

but in TF/Keras:

ˋˋˋ
while True:
     model.fit(data, epochs=1, Callback_that_uses_make_checkpoint())
ˋˋˋ

IMO this change in workflow should be documented.

**Comment by dberenbaum** [comment]
> Hmm ... I'm still lost re the error you had before.

Here's some context if it helps:

> emre May 25th at 2:43 PM
> Hello core! I'm working on a checkpoints project: https://github.com/iterative/get-started-checkpoints  It seems to run fine in dvclive and basic branches, but signal-file and python-api seems to eat my logs.csv and spitting this error:
> Screenshot_20210525-214311_Termux.jpg 
> Screenshot_20210525-214311_Termux.jpg
> 
> emre  8 days ago
> I checked several times that logs.csv is there when I start running.
> 
> emre  8 days ago
> I will report a bug but is this something happened before or may be because of me doing something wrong?
> 
> Dave Berenbaum  8 days ago
> DVC will drop logs.csv at the start, and you need to be generating that output in each checkpoint. Looking at signal-file, it looks like you aren’t writing logs.csv until after the checkpoint is generated. Happy to take a closer look at this repo (or the repo that generates it) at some point if you want.
> 
> emre  7 days ago
> I’m generating the output at every step, but I use a Tensorflow callback for make_checkpoint at the end of each epoch. It’s not like in PyTorch where you can write a loop. This means (1) make_checkpoint and (2) save logs.csv. From the code in dvc-checkpoints-mnist it looks like this is the reason. This error didn’t appear until I’ve updated for indefinite training.
> I’ll update the code to save the model, write logs.csv and call make_checkpoint in the callback.

**Comment by shcheklein** [comment]
Got it! Thanks. A few more questions:

- @iesahin where and how did you call `make_checkpoint` initially? if it's callbacks based you should have used a callback, no?
- does is it mean that users have to implement these callbacks? Is there a plan to implement them? My concern that we have a get started example that looks too complicated, doesn't look like a "happy path" (should be one `import`, very regular train loop, profit)

It is all probably related to the https://github.com/iterative/dvclive/issues/5#issuecomment-853278764

If we consider TF/Pytorch too level, should we use something simpler like lighting then to make example simpler?

**Comment by shcheklein** [comment]
One more question:

why callback code has to be so complicated? can we use `make_checkpoint` and dvclive's logger to write CSV?

**Comment by shcheklein** [comment]
I think this is also outdated.
