### ISSUE TITLE
repos: don't use `dataset-registry` to store models, intermediate artifacts, etc

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#48]
In some example repos I see:

```ini
[core]
    remote = storage
['remote "storage"']
    url = https://remote.dvc.org/dataset-registry
```

We should not be using `dataset-registry` as a remote for these repos. For every repo we use a separate remote now, e.g. here is the `example-get-started`:

https://github.com/iterative/example-get-started/blob/master/.dvc/config#L1-L4

```ini
[core]
    remote = storage
['remote "storage"']
    url = https://remote.dvc.org/get-started
```

**Comment by iesahin** [comment]
I'm using `https://remote.dvc.org/get-started` for the newer 3 repositories. Should I change each of them to different remotes?

**Comment by shcheklein** [comment]
@iesahin it's more or less fine if we intend to use them in the get started. There are though clear benefits to split every repo into a separate remote - less chances to mess up with data :)

**Comment by iesahin** [comment]
All three GS repositories use the same data and artifacts in prepare and preprocess steps. I think accidental collusions are not that probable and keeping under the same remote may be easier for maintenance :)

**Comment by shcheklein** [comment]
> and keeping under the same remote may be easier for maintenance

that's my point. I think it might be easier to maintain when they are separate. E.g. you can delete one w/o affecting other repos. 

> All three GS repositories use the same data and artifacts in prepare and preprocess steps.

yep, and we are saving some space this way, and that's what I would recommend in the real life scenario, but in this case it's not that important for us, right?

> I think accidental collusions are not that probable

no, I'm not worried about this at all. It's more about simplicity in cleaning them if needed, etc.

**Comment by shcheklein** [comment]
I think this is fixed now.
