### ISSUE TITLE
mnist examples: simplify data layout, params, etc

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#54]
- don't use `.gz`
- don't use deeply nested folders
- remove params that are not relevant

**Comment by shcheklein** [comment]
Also data is too large. It takes too long to download I think.

**Comment by iesahin** [comment]
> Also data is too large. It takes too long to download I think.

The raw data itself is not too large (31MB), the prepared/preprocessed data is large. Those can be generated by the user in the first run. I'll take care of this.

**Comment by shcheklein** [comment]
Optimize .gitignore - it's too complicated and redundant

**Comment by shcheklein** [comment]
Not using cache for large files is not a regular pattern - we are breaking the regular flow here

**Comment by iesahin** [comment]
> Optimize .gitignore - it's too complicated and redundant

That is the standard Github Python `.gitignore` + DVC stuff. People may use different editors, venv folders etc. 

> Not using cache for large files is not a regular pattern - we are breaking the regular flow here

I think it's better to merge `prepare` and `preprocess` steps in experiments (and checkpoints) projects. The largest files are products of `preprocess` step and I think I can eliminate it.

**Comment by shcheklein** [comment]
> That is the standard Github Python .gitignore + DVC stuff. People may use different editors, venv folders etc.

Yep, it makes sense. A few points why we try to keep it simple:

- the way we write get started is we show it from the very beginning - `git init`, `dvc init`, etc. So, any extra stuff that is not directly related distract people
- related to the previous point - it easier to show what's going on when you do `dvc add` you they see one single entry in the file instead of a production ready `.gitignore`
- it becomes a bit opinionated - Python-specific (DVC is language agnostic), include everything beforehand vs keeping it simple and add stuff that is needed, etc, etc

> I think it's better to merge prepare and preprocess steps in experiments (and checkpoints) projects. The largest files are products of preprocess step and I think I can eliminate it.

yep, it might be, hard to tell. Need to see the text for the docs to see if it simplifies it or not, which one is better.

**Comment by iesahin** [comment]
>     * the way we write get started is we show it from the very beginning - `git init`, `dvc init`, etc. So, any extra stuff that is not directly related distract people

The *Get Started with Experiments* document shouldn't start from `git init` or `dvc init`, otherwise it turns into another pipelines document. We should assume there is already an existing project. I plan to remove all Git tags related to pipelines and source code, we'll have some kind of "let there be a project" structure both in the repository and the document. Tags will be used for experiments. It will also be better for Studio.

**Comment by dberenbaum** [comment]
Assuming there is a project and probably a git repo makes sense, but I'm not sure we should assume `dvc init` has been run. Ideally, this is a standalone intro for people who have never used DVC before.

**Comment by iesahin** [comment]
I think we can close this now?
