### ISSUE TITLE
example-get-started: generalize CML workflow

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#58]
Right now for some reason (simplicity?) we compare everything with the bigrams experiment.

- we depend on a specific tag name
- when we do a PR to that repo - report name is misleading and not very meaningful

**Comment by shcheklein** [comment]
cc @casperdcl

**Comment by casperdcl** [comment]
> we compare everything with the bigrams experiment

Yes it's for simplicity (made most sense to me at the time - do you have other suggestions?)

> report name is misleading

https://github.com/iterative/example-repos-dev/blob/279b255646d5400cb9ea689302145ec6eb9c5f87/example-get-started/code/.github/workflows/cml.yaml#L15-L25

are you referring to improving L15 above? Or L24?

**Comment by shcheklein** [comment]
> are you referring to improving L15 above? Or L24?

L24. `workspace` term is probably wrong (from the end-user perspective) - we are comparing their commit to some previous attempt. It's not workspace for them.

> do you have other suggestions?

What would be a meaningful CML integration? One example (to my mind). If I do a PR - it should be comparing it with the latest changes in the main branch. When it lands it's merged, or a new commit pushed directly to the main branch - that's a good question. Probably diff doesn't make sense anymore - just show its actual state. Or show it compared to the previous commit.

------

Depending on a hard coded tag name (which is not special and might change) is fragile. And in this case it's not clear why that one specifically.

**Comment by casperdcl** [comment]
I think `dvc metrics diff` uses the term `workspace` though...

**Comment by daavoo** [comment]
Shouldn't the `cml.yaml` workflow also run the train script (i.e. with `pip install -r requirements.txt && dvc repro`) ?? 

I might be missing some context but the repository is used in some DVC Studio demos to showcase how to modify `params` with the `Run new experiment` button. I found it unexpected for the repository to don't actually run the train script with the modified `params` but just to report metrics comparing some hardcoded `refs`.

**Comment by casperdcl** [comment]
Hmm the current code is geared towards you running the experiment locally & using CML for reporting from the CI. The DVC Studio use case would indeed need training as part of the CI too.
