### ISSUE TITLE
Epic: add badges in all projects

### ISSUE THREAD

**Issue by casperdcl** [iterative/example-repos-dev#60]
add badges as per https://github.com/iterative/dvc.org/issues/234#issuecomment-848243511 - particularly the JSON/YAML ones.

- [ ] #87

**Comment by daavoo** [comment]
`View in Studio`?: https://github.com/iterative/dvc.org/issues/234#issuecomment-920716784

**Comment by casperdcl** [comment]
can't get the studio icon to show up in shields.io badges yet https://github.com/simple-icons/simple-icons/pull/5674#issuecomment-839885799

**Comment by mvshmakov** [comment]
The maintainer says that it would be great to create an issue about it to access the popularity of the Studio through "other metrics". Should we do it if we can't simply add the badge at the moment?

**Comment by casperdcl** [comment]
we could self-host a badge... basically e.g. auto-redirect e.g. `https://badge.iterative.ai/<ARGS>?logo=Studio&<OPTS>` to `https://img.shields.io/<ARGS>?logo=data:image/png;base64,<STUDIO_LOGO>&<OPTS>`

CC @shcheklein @rogermparent

**Comment by rogermparent** [comment]
> `https://badge.iterative.ai/<ARGS>?logo=Studio&<OPTS>` to `https://img.shields.io/<ARGS>?logo=data:image/png;base64,
> <STUDIO_LOGO_BASE64>&<OPTS>`

Sounds possible, though we'd need a CF rule or a new Heroku app as opposed to tossing it into `iterative.ai`'s server since the `badge` subdomain points to a new site.

**Comment by shcheklein** [comment]
I think this can be closed, the `example-get-started` has the badge already, the new project (`example-get-started-experiments`) will have them as well. Everything else is less critical. Let's open separate issues for them if needed.
