### ISSUE TITLE
get-started-experiments: add `models/model.h5` to `.gitignore` in `generate.bash`

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#65]
As we began to use `--outs-no-cache` for the model, it should be added to `.gitignore` manually.

**Comment by shcheklein** [comment]
Why do we use `--outs-no-cache`? Models are generally pretty large files and do not fit well into Git.

**Comment by iesahin** [comment]
Not to track them in DVC. I see them as _created-on-demand_ files. 

Each `dvc exp run` produces a slightly different model file and `dvc pull` tries to find them in the remote, complains if not found. I think a new user shouldn't see warnings. Alternatively, I can upload all of them, they are not large files (4-5MB) but too many to keep around for each experiment. 

Another reason was to run the initial `dvc exp run` after cloning. If `model.h5` is downloaded, nothing needs to be run. 

@shcheklein

**Comment by shcheklein** [comment]
Thanks, Emre, for the explanation. Yes, the general workflow is to store them (it take time to retrain, when you deploy it - it's better to have it saved somewhere + you want to have it somewhere around as a backup, for CI/CD - you want to take it and run tests, etc, etc).

> Another reason was to run the initial dvc exp run after cloning. If model.h5 is downloaded, nothing needs to be run.

Yep, I think this is find. This a "saved" experiment. It makes sense that it has all parts of it committed.

> Each dvc exp run produces a slightly different model file and dvc pull tries to find them in the remote, complains if not found. I think a new user shouldn't see warnings.

We should push them I think, I don't see any reasons not to do this. I'm not sure I understand this point to be honest though. Could you clarify please?

**Comment by iesahin** [comment]
My basic intention is to let the user run `dvc exp run` in the first try and run an experiment. Getting a saved experiment with `dvc pull` doesn't look like the user is experimenting. 

If you rather would like to see this first experiment as _saved and retrieved_ from the remote, then it's all right for me to convert to a cached file.

**Comment by dberenbaum** [comment]
> `dvc pull` tries to find them in the remote, complains if not found.

I think this is related to https://github.com/iterative/dvc/issues/5913. Ideally, I think you should be able to create a pipeline with a model output tracked by dvc, push it without running the pipeline, and then pull on a different machine without getting an error (a clear warning might be okay). This is a common workflow for CML.
