### ISSUE TITLE
Include `devcontainer.json` as part of the example repos

### ISSUE THREAD

**Issue by daavoo** [iterative/example-repos-dev#74]
I think it would be nice to include a custom [Codespaces environment](https://docs.github.com/en/codespaces/customizing-your-codespace/configuring-codespaces-for-your-project) to make the example repositories directly usable in Codespaces without extra setup steps.

**Comment by iesahin** [comment]
I think it provides a nice addition on top of Katacoda, and frankly, I'm all for something to replace Katacoda. :)

**Comment by shcheklein** [comment]
It's done for the example-get-started repo, we can do the same for everything else now.

**Comment by aguschin** [comment]
Added `.devcontainer/` to #109

**Comment by shcheklein** [comment]
Closing since it's not part of the regular workflow and is done for the main repos.
