### ISSUE TITLE
experiments: use pytorch or other lightweight lib

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#76]
One of the common problems of TF is that it always lacks a support for Python or hardware and it takes time to upgrade it.

Does it makes sense to use PyTorch? Is it simpler in that sense?

One of the most recent examples- I can't run the `experiments-get-started` on M1.

We need to have get started repos and accessible as possible.

**Comment by iesahin** [comment]
PyTorch was more heavyweight the last time I checked in terms of RAM. TF runs on Katacoda, PyTorch does not. 

Apple M1 needs a separate installation for Tensorflow: https://developer.apple.com/metal/tensorflow-plugin/

PyTorch seems no different: https://github.com/pytorch/pytorch/issues/56333

There are instructions for both here: https://naturale0.github.io/2021/01/29/setting-up-m1-mac-for-both-tensorflow-and-pytorch

From the looks of this latter post, PyTorch runs on Rosetta without native support on M1. TF supports native arm64. 

I can think of a solution, e.g., separate project for M1, a project with only sklearn, etc. I still consider M1 as a moving target, so supporting it requires some separate maintenance. @shcheklein

**Comment by dberenbaum** [comment]
I can confirm that PyTorch is a simpler install right now on M1 (see https://github.com/pytorch/pytorch/issues/56333#issuecomment-857837565). However, I agree that it's unclear that this will continue to be true going forward, or that PyTorch is inherently less troublesome to install.

**Comment by iesahin** [comment]
We may also use conda for the example projects and it seems both TF and PyTorch will work that way on M1. I usually don't like to have additional/restrictive dependencies for the projects but if ``conda makes life easier for the newcomer, we can think of it.

**Comment by shcheklein** [comment]
Closing in favor of https://github.com/iterative/example-repos-dev/issues/113
