### ISSUE TITLE
Create an example project for `dvclive` separate from `example-dvc-checkpoints`. 

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#81]
We can create a separate project for DVCLive. 

- It can have multiple branches for each ML framework listed in https://dvc.org/doc/dvclive/user-guide/ml-frameworks
- Or it's possible to create similar repositories for each ML framework. (`example-dvclive-keras`, `example-dvclive-pytorch` ...) These can also be templates for users when creating projects.

**Comment by iesahin** [comment]
This may lead to "repository explosion."

**Comment by iesahin** [comment]
I've added DVCLive as a final tag to `example-dvc-experiments` in #95 Hence, the final state of the experiments project now contains DVCLive. PTAL @shcheklein 

I'm waiting for iterative/dvc#6920 to generate the new repository. I can rollback to DVC 2.7 if it's not resolved.

**Comment by shcheklein** [comment]
I think both example projects are using `dvclive` now. Closing this.
