### ISSUE TITLE
`example-dvc-experiments`: Improvements

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#85]
What do we need to make https://github.com/iterative/example-dvc-experiments useful for the Studio?

- [x] #86
- [x] #83 

_Originally posted by @shcheklein in https://github.com/iterative/example-repos-dev/issues/79#issuecomment-911902501_

**Comment by dberenbaum** [comment]
Why do metrics need to be cached for Studio?

**Comment by shcheklein** [comment]
No need them to be cached (for plots and metrics). Model files I would expected to be cached and _not_ gitignored. Intermediate artifacts - depends. Probably it's fine to avoid caching 70K images and ignore them. But we should really fix the DVC performances for this. Repo becomes suboptimal, artificial because of the limitations that we have.

**Comment by shcheklein** [comment]
I would rename the ticket also - it's not about Studio, for any scenario I would expect model files to be DVC-tracked (and may be some important intermediate artifacts).

**Comment by dberenbaum** [comment]
Is there a reason that `data/images` has `cache: false` in `dvc.yaml`? Was caching the output causing some issue?

**Comment by iesahin** [comment]
`data/images` is extracted from `data/images.tar.gz` and contains 70K small files. `dvc push/pull` takes considerable time when we cache it. (We might need "cache but don't send to remote" setting for files and dirs, but that's a separate discussion.)

**Comment by dberenbaum** [comment]
> We might need "cache but don't send to remote" setting for files and dirs, but that's a separate discussion.

That's in https://github.com/iterative/dvc/issues/2095 and probably is pretty easy now that we have https://github.com/iterative/dvc/pull/6486. We just need a way to specify "none."
